default: &default
  adapter: postgresql
  pool: 5
  timeout:  5000

development:
  <<: *default
  database: peerstreet_challenge

test:
  <<: *default
  database: test_db

production:
  <<: *default
  database: peerstreet_challenge

